### ISSUE TITLE
你好，第一个分页功能，如何写配置文件呢？

### ISSUE THREAD

**Issue by otizis** [pnoker/mybatisGenerator#1]
你好，第一个分页功能，如何写配置文件呢？

**Comment by pnoker** [comment]
这个分页功能不是写配置文件的， 以上提到的代码都是 Mybatis Generator的源码，修改步骤中的源码，然后重新打包生成一个jar之后，再自动生成Mapping、Model、Dao就有分页功能了。

**Comment by otizis** [comment]
明白了，我将你的当作插件放进去，默认加载的是官方的没效果。
可以了，多谢。
